### ISSUE TITLE
Can't import eth_retry

### ISSUE THREAD

**Issue by T1murKO** [BobTheBuidler/eth_retry#20]
Mac os 13.0 
Python 3.10

Happens starting from 0.1.12

  File "/opt/homebrew/anaconda3/envs/arb-bot/lib/python3.10/site-packages/multicall/call.py", line 3, in <module>
    import eth_retry
  File "/opt/homebrew/anaconda3/envs/arb-bot/lib/python3.10/site-packages/eth_retry/__init__.py", line 1, in <module>
    from eth_retry.eth_retry import auto_retry
  File "/opt/homebrew/anaconda3/envs/arb-bot/lib/python3.10/site-packages/eth_retry/eth_retry.py", line 32, in <module>
    CoroutineFunction = Function[Awaitable[T]]
  File "/opt/homebrew/anaconda3/envs/arb-bot/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/opt/homebrew/anaconda3/envs/arb-bot/lib/python3.10/typing.py", line 1056, in __getitem__
    params = _prepare_paramspec_params(self, params)
  File "/opt/homebrew/anaconda3/envs/arb-bot/lib/python3.10/typing.py", line 244, in _prepare_paramspec_params
    _check_generic(cls, params, len(cls.__parameters__))
  File "/opt/homebrew/anaconda3/envs/arb-bot/lib/python3.10/typing.py", line 231, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
TypeError: Too few arguments for typing.Callable[~P, ~T]; actual 1, expected 2

**Comment by BobTheBuidler** [comment]
Thanks for pointing this out! Looks like I had an issue with my import handling for Python 3.10.
PR #22 Fixes this. I'll publish release 0.1.14 now with the changes.

**Comment by BobTheBuidler** [comment]
Scratch that, it will be 0.1.15

**Comment by stas** [comment]
Running `coverage` still fails with the latest version:

```sh
coverage run --source=app setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing HTTP_API.egg-info/PKG-INFO
writing dependency_links to HTTP_API.egg-info/dependency_links.txt
writing requirements to HTTP_API.egg-info/requires.txt
writing top-level names to HTTP_API.egg-info/top_level.txt
reading manifest file 'HTTP_API.egg-info/SOURCES.txt'
writing manifest file 'HTTP_API.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setup(
  File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/pypy/lib/pypy3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/pypy/lib/pypy3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/pypy/lib/pypy3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/command/test.py", line 223, in run
    self.run_tests()
  File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/command/test.py", line 226, in run_tests
    test = unittest.main(
  File "/opt/pypy/lib/pypy3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/opt/pypy/lib/pypy3.9/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/opt/pypy/lib/pypy3.9/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/opt/pypy/lib/pypy3.9/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/opt/pypy/lib/pypy3.9/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/opt/pypy/lib/pypy3.9/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/opt/pypy/lib/pypy3.9/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/opt/pypy/lib/pypy3.9/site-packages/setuptools/command/test.py", line 56, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/opt/pypy/lib/pypy3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/app/app/gauges/__init__.py", line 3, in <module>
    from .model import Gauge  # noqa
  File "/app/app/gauges/model.py", line 2, in <module>
    from multicall import Call, Multicall
  File "/opt/pypy/lib/pypy3.9/site-packages/multicall-0.7.0-py3.9.egg/multicall/__init__.py", line 2, in <module>
    from multicall.call import Call
  File "/opt/pypy/lib/pypy3.9/site-packages/multicall-0.7.0-py3.9.egg/multicall/call.py", line 3, in <module>
    import eth_retry
  File "/opt/pypy/lib/pypy3.9/site-packages/eth_retry/__init__.py", line 1, in <module>
    from eth_retry.eth_retry import auto_retry
  File "/opt/pypy/lib/pypy3.9/site-packages/eth_retry/eth_retry.py", line 36, in <module>
    CoroutineFunction = Function[P, Awaitable[T]]
  File "/opt/pypy/lib/pypy3.9/typing.py", line 277, in inner
    return func(*args, **kwds)
  File "/opt/pypy/lib/pypy3.9/typing.py", line 768, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/opt/pypy/lib/pypy3.9/site-packages/typing_extensions.py", line 106, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too many parameters for typing.Callable[[~P], ~T]; actual 2, expected 1
```

Eg. build:
https://github.com/velodrome-finance/api/actions/runs/3788270290/jobs/6440880280

**Comment by MicolX** [comment]
Hi, has this issue been solved or any workaround? I also encounter this problem on version 0.1.18
